export const IDEMPOTENCY_SCOPE_PAYMENT_CREATE = 'payment.create';

export const AUDIT_ACTIONS = {
  PAYMENT_CREATED: 'PAYMENT_CREATED',
  PAYMENT_INITIATED: 'PAYMENT_INITIATED',
  PAYMENT_PROCESSING: 'PAYMENT_PROCESSING',
  PAYMENT_PENDING: 'PAYMENT_PENDING',
  PAYMENT_SUCCEEDED: 'PAYMENT_SUCCEEDED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_EXPIRED: 'PAYMENT_EXPIRED',
  PAYMENT_CANCELLED: 'PAYMENT_CANCELLED',
  WEBHOOK_RECEIVED: 'WEBHOOK_RECEIVED',
  WEBHOOK_VERIFIED: 'WEBHOOK_VERIFIED',
  WEBHOOK_REJECTED: 'WEBHOOK_REJECTED',
  RECONCILIATION_STARTED: 'RECONCILIATION_STARTED',
  RECONCILIATION_COMPLETED: 'RECONCILIATION_COMPLETED',
  REFUND_CREATED: 'REFUND_CREATED',
  ADMIN_ACTION: 'ADMIN_ACTION',
} as const;

export const DEFAULT_PAGE_SIZE = 25;
export const MAX_PAGE_SIZE = 100;
